spring.application.name=LeadManagementProject

spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Gemini ai api 

gemini.api.key=${GEMINI_API_KEY}


fb.page-access-token=${FB_PAGE_ACCESS_TOKEN}
fb.app.async-core-pool-size=5